# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
    matrix:
      Python38:
        python.version: '3.8'
    maxParallel: 1

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip && pip install --upgrade robotframework robotframework-selenium2library && npm install chromedriver
    displayName: 'Install dependencies'

  - bash: robot -x outputunit.xml -d Results/ApiTestResults Tests/openWebPage.robot
    displayName: 'Run Robot Scripts'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'report.html'
      displayName: 'Publish Test Results outputxunit.xml'
      